# Generated by Django 6.0.6 on 2026-07-01 16:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('persona', 'Persona Natural'), ('empresa', 'Empresa'), ('ambos', 'Persona y Empresa')], default='persona', max_length=20)),
                ('nombre_personal', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Mexico', max_length=100)),
                ('plan', models.CharField(choices=[('basico', 'Plan Básico'), ('profesional', 'Plan Profesional'), ('empresa', 'Plan Empresa')], default='basico', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('color_primario', models.CharField(default='#3498db', max_length=7)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('pastel', 'Pastel'), ('tapiceria', 'Tapicería'), ('otro', 'Otro Servicio')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente'), ('contador', 'Contador'), ('visualizador', 'Solo visualización')], default='vendedor', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('puede_crear_cotizaciones', models.BooleanField(default=True)),
                ('puede_eliminar_cotizaciones', models.BooleanField(default=False)),
                ('puede_ver_reportes', models.BooleanField(default=False)),
                ('puede_gestionar_usuarios', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='cotizador_project.cliente')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cotizador_project.organization'),
        ),
        migrations.CreateModel(
            name='PastelServicio',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cotizador_project.servicio')),
                ('color', models.CharField(max_length=100)),
                ('tipo_pastel', models.CharField(max_length=100)),
                ('pisos', models.IntegerField()),
                ('sabor', models.CharField(max_length=100)),
                ('decoracion', models.TextField(blank=True)),
                ('peso_aproximado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Pastel',
                'verbose_name_plural': 'Pasteles',
            },
            bases=('cotizador_project.servicio',),
        ),
        migrations.CreateModel(
            name='TapiceriaServicio',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cotizador_project.servicio')),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('medidas', models.CharField(max_length=100)),
                ('tipo_mueble', models.CharField(max_length=100)),
                ('estado_actual', models.CharField(max_length=100)),
                ('requiere_instalacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tapicería',
                'verbose_name_plural': 'Tapicerías',
            },
            bases=('cotizador_project.servicio',),
        ),
        migrations.AddField(
            model_name='servicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='cotizador_project.organization'),
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizador_project.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_project.servicio')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['organization', 'estado'], name='cotizador_p_organiz_d0f7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['organization', 'cliente'], name='cotizador_p_organiz_535296_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['organization', '-creado'], name='cotizador_p_organiz_e83689_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('organization', 'numero'), name='unique_cotizacion_numero_por_org'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['organization', 'nombre'], name='cotizador_p_organiz_939312_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['organization', 'email'], name='cotizador_p_organiz_2b5de0_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_cliente_email_por_org'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['organization', 'tipo'], name='cotizador_p_organiz_de9fa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('organization', 'nombre'), name='unique_servicio_nombre_por_org'),
        ),
    ]
