# Generated by Django 6.0.6 on 2026-07-01 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('gerente', 'Gerente'), ('contador', 'Contador'), ('visualizador', 'Solo visualización')], default='vendedor', max_length=20)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField()),
                ('invitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
