# Generated by Django 6.0.6 on 2026-07-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_project', '0003_alter_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('decimal', 'Decimal'), ('boolean', 'Booleano'), ('color', 'Color'), ('select', 'Lista')], max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Atributo',
                'verbose_name_plural': 'Plantillas de Atributo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AtributoPlantillaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opción de Atributo',
                'verbose_name_plural': 'Opciones de Atributo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
            ],
            options={
                'verbose_name': 'Valor de Cotización',
                'verbose_name_plural': 'Valores de Cotización',
            },
        ),
        migrations.CreateModel(
            name='ServicioValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
            ],
            options={
                'verbose_name': 'Valor de Servicio',
                'verbose_name_plural': 'Valores de Servicio',
            },
        ),
        migrations.RemoveField(
            model_name='pastelservicio',
            name='servicio_ptr',
        ),
        migrations.RemoveField(
            model_name='tapiceriaservicio',
            name='servicio_ptr',
        ),
        migrations.RemoveIndex(
            model_name='servicio',
            name='cotizador_p_organiz_de9fa2_idx',
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['organization', 'categoria'], name='cotizador_p_organiz_4e7765_idx'),
        ),
        migrations.AddField(
            model_name='atributoplantilla',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_atributo', to='cotizador_project.organization'),
        ),
        migrations.AddField(
            model_name='atributoplantillaopcion',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cotizador_project.atributoplantilla'),
        ),
        migrations.RenameModel(
            old_name='ItemCotizacion',
            new_name='CotizacionDetalle',
        ),
        migrations.AddField(
            model_name='cotizacionvalor',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_project.atributoplantilla'),
        ),
        migrations.AddField(
            model_name='cotizacionvalor',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='cotizador_project.cotizaciondetalle'),
        ),
        migrations.AddField(
            model_name='serviciovalor',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_project.atributoplantilla'),
        ),
        migrations.AddField(
            model_name='serviciovalor',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='cotizador_project.servicio'),
        ),
        migrations.DeleteModel(
            name='PastelServicio',
        ),
        migrations.DeleteModel(
            name='TapiceriaServicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
        migrations.AddIndex(
            model_name='atributoplantilla',
            index=models.Index(fields=['organization', 'categoria'], name='cotizador_p_organiz_0e2545_idx'),
        ),
        migrations.AddConstraint(
            model_name='atributoplantilla',
            constraint=models.UniqueConstraint(fields=('organization', 'categoria', 'nombre'), name='unique_plantilla_attr_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='atributoplantillaopcion',
            constraint=models.UniqueConstraint(fields=('atributo', 'valor'), name='unique_opcion_por_atributo'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionvalor',
            constraint=models.UniqueConstraint(fields=('detalle', 'atributo'), name='unique_valor_por_detalle_atributo'),
        ),
        migrations.AddConstraint(
            model_name='serviciovalor',
            constraint=models.UniqueConstraint(fields=('servicio', 'atributo'), name='unique_valor_por_servicio_atributo'),
        ),
    ]
