# Generated by Django 6.0.6 on 2026-07-03 17:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_project', '0004_atributoplantilla_atributoplantillaopcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5),
        ),
    ]
