# Generated by Django 6.0.6 on 2026-07-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_project', '0006_organization_calle_organization_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('608', '608 - Demás ingresos'), ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 - Ingresos por intereses'), ('616', '616 - Sin obligaciones fiscales'), ('621', '621 - Incorporación Fiscal'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 - Régimen Simplificado de Confianza')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='uso_cfdi_default',
            field=models.CharField(blank=True, choices=[('G01', 'G01 - Adquisición de mercancías'), ('G02', 'G02 - Devoluciones, descuentos o bonificaciones'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('I04', 'I04 - Equipo de cómputo y accesorios'), ('I08', 'I08 - Otra maquinaria y equipo'), ('D01', 'D01 - Honorarios médicos, dentales y gastos hospitalarios'), ('D10', 'D10 - Pagos por servicios educativos (colegiaturas)'), ('P01', 'P01 - Por definir'), ('S01', 'S01 - Sin efectos fiscales'), ('CP01', 'CP01 - Pagos')], max_length=10, null=True),
        ),
    ]
