# Generated by Django 6.0.6 on 2026-07-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_project', '0007_organization_razon_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('color_primario', models.CharField(blank=True, max_length=7, null=True)),
                ('color_fondo', models.CharField(blank=True, max_length=7, null=True)),
                ('color_superficie', models.CharField(blank=True, max_length=7, null=True)),
                ('color_texto', models.CharField(blank=True, max_length=7, null=True)),
                ('color_menu_fondo', models.CharField(blank=True, max_length=7, null=True)),
                ('color_menu_texto', models.CharField(blank=True, max_length=7, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'nombre'), name='unique_sucursal_nombre_por_org')],
            },
        ),
    ]
