# Generated by Django 6.0.6 on 2026-07-02 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizador_project', '0004_atributoplantilla_atributoplantillaopcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FIBRA',
                'verbose_name_plural': 'FIBRAs',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='DividendoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_por_certificado', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividendos', to='fibras_app.fibra')),
            ],
            options={
                'verbose_name': 'Dividendo Histórico',
                'verbose_name_plural': 'Dividendos Históricos',
                'ordering': ['fecha_pago'],
                'indexes': [models.Index(fields=['fibra', 'fecha_pago'], name='fibras_app__fibra_i_899a09_idx')],
                'constraints': [models.UniqueConstraint(fields=('fibra', 'fecha_pago'), name='unique_dividendo_por_fibra_fecha')],
            },
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio_cierre', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_apertura', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('precio_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('precio_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volumen', models.BigIntegerField(blank=True, null=True)),
                ('fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='fibras_app.fibra')),
            ],
            options={
                'verbose_name': 'Precio Histórico',
                'verbose_name_plural': 'Precios Históricos',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fibra', 'fecha'], name='fibras_app__fibra_i_507f0b_idx')],
                'constraints': [models.UniqueConstraint(fields=('fibra', 'fecha'), name='unique_precio_por_fibra_fecha')],
            },
        ),
        migrations.CreateModel(
            name='SimulacionInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('comparacion', 'Comparación'), ('dca', 'Aportaciones periódicas')], max_length=20)),
                ('parametros', models.JSONField()),
                ('resultado', models.JSONField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_inversion', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Simulación de Inversión',
                'verbose_name_plural': 'Simulaciones de Inversión',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['organization', '-creado'], name='fibras_app__organiz_60b19e_idx')],
            },
        ),
    ]
