# Generated by Django 6.0.6 on 2026-07-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizador_project', '0004_atributoplantilla_atributoplantillaopcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#e74c3c', max_length=7)),
                ('icono', models.CharField(blank=True, default='💸', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('icono', models.CharField(blank=True, default='💰', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_ingreso', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Categoría de Ingreso',
                'verbose_name_plural': 'Categorías de Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='finanzas_app.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_creados', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='finanzas_app.categoriaingreso')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_creados', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriagasto',
            index=models.Index(fields=['organization'], name='finanzas_ap_organiz_193abb_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriagasto',
            constraint=models.UniqueConstraint(fields=('organization', 'nombre'), name='unique_categoria_gasto_por_org'),
        ),
        migrations.AddIndex(
            model_name='categoriaingreso',
            index=models.Index(fields=['organization'], name='finanzas_ap_organiz_33ce7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriaingreso',
            constraint=models.UniqueConstraint(fields=('organization', 'nombre'), name='unique_categoria_ingreso_por_org'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['organization', 'fecha'], name='finanzas_ap_organiz_1e783f_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['organization', 'categoria'], name='finanzas_ap_organiz_12cf66_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['organization', 'fecha'], name='finanzas_ap_organiz_e225d0_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['organization', 'categoria'], name='finanzas_ap_organiz_6f8c76_idx'),
        ),
    ]
