# Generated by Django 6.0.6 on 2026-07-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizador_project', '0004_atributoplantilla_atributoplantillaopcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url_data', models.URLField()),
                ('png_data', models.BinaryField()),
                ('color_fg', models.CharField(default='#000000', max_length=7)),
                ('color_bg', models.CharField(default='#FFFFFF', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='qr_logos/')),
                ('forma', models.CharField(choices=[('square', 'Cuadrado'), ('rounded', 'Redondeado')], default='square', max_length=20)),
                ('descargado_veces', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_creados', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codigos', to='cotizador_project.organization')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['organization', 'creado'], name='qr_app_codi_organiz_654913_idx')],
            },
        ),
    ]
