# Generated by Django 6.0.6 on 2026-07-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_project', '0004_atributoplantilla_atributoplantillaopcion_and_more'),
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codigos', to='cotizador_project.cotizacion'),
        ),
    ]
