# Generated by Django 6.0.6 on 2026-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_codigoqr_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='color_gradiente',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='forma_ojos',
            field=models.CharField(choices=[('square', 'Cuadrado'), ('rounded', 'Redondeado'), ('circle', 'Círculos'), ('gapped_square', 'Cuadrado con espacio'), ('horizontal_bars', 'Barras horizontales'), ('vertical_bars', 'Barras verticales')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='gradiente_tipo',
            field=models.CharField(choices=[('none', 'Sin degradado (color sólido)'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('radial', 'Radial'), ('square', 'Cuadrado (esquinas)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='margen',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='forma',
            field=models.CharField(choices=[('square', 'Cuadrado'), ('rounded', 'Redondeado'), ('circle', 'Círculos'), ('gapped_square', 'Cuadrado con espacio'), ('horizontal_bars', 'Barras horizontales'), ('vertical_bars', 'Barras verticales')], default='square', max_length=20),
        ),
    ]
